EnterpriseWebApplication/Areas/Admin/Pages/Role/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EnterpriseWebApplication.Areas.Admin.Pages.Role
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AddModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public class InputModel
        {
            public string ID { set; get; }

            [Required(ErrorMessage = "Role required")]
            [Display(Name = "Role")]
            [StringLength(100, ErrorMessage = "{0} must be at least from {2} to {1} characters.", MinimumLength = 3)]
            public string Name { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool IsUpdate { set; get; }

        public IActionResult OnGet() => NotFound("Not Found");
        public IActionResult OnPost() => NotFound("Not Found");


        public IActionResult OnPostStartNewRole()
        {
            StatusMessage = "Role information";
            IsUpdate = false;
            ModelState.Clear();
            return Page();
        }

        public async Task<IActionResult> OnPostStartUpdate()
        {
            StatusMessage = null;
            IsUpdate = true;
            if (Input.ID == null)
            {
                StatusMessage = "Error: No information about this role";
                return Page();
            }
            var result = await _roleManager.FindByIdAsync(Input.ID);
            if (result != null)
            {
                Input.Name = result.Name;
                ViewData["Title"] = "Update role : " + Input.Name;
                ModelState.Clear();
            }
            else
            {
                StatusMessage = "Error: No information about this role ID = " + Input.ID;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddOrUpdate()
        {

            if (!ModelState.IsValid)
            {
                StatusMessage = null;
                return Page();
            }

            if (IsUpdate)
            {
                if (Input.ID == null)
                {
                    ModelState.Clear();
                    StatusMessage = "Error: No information about this role";
                    return Page();
                }
                var result = await _roleManager.FindByIdAsync(Input.ID);
                if (result != null)
                {
                    result.Name = Input.Name;

                    var roleUpdateRs = await _roleManager.UpdateAsync(result);
                    if (roleUpdateRs.Succeeded)
                    {
                        StatusMessage = "Updated";
                    }
                    else
                    {
                        StatusMessage = "Error: ";
                        foreach (var er in roleUpdateRs.Errors)
                        {
                            StatusMessage += er.Description;
                        }
                    }
                }
                else
                {
                    StatusMessage = "Error: Cannot find updated role";
                }

            }
            else
            {
                var newRole = new IdentityRole(Input.Name);

                var rsNewRole = await _roleManager.CreateAsync(newRole);
                if (rsNewRole.Succeeded)
                {
                    StatusMessage = $"New role created: {newRole.Name}";
                    return RedirectToPage("./Index");
                }
                else
                {
                    StatusMessage = "Error: ";
                    foreach (var er in rsNewRole.Errors)
                    {
                        StatusMessage += er.Description;
                    }
                }
            }

            return Page();

        }
    }
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/AddUserRole.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EnterpriseWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EnterpriseWebApplication.Areas.Admin.Pages.Role
{
    [Authorize(Roles = "Admin")]
    public class AddUserRoleModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;


        public AddUserRoleModel(RoleManager<IdentityRole> roleManager,
                            UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public class InputModel
        {
            [Required]
            public string ID { set; get; }
            public string Name { set; get; }
            public string[] RoleNames { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool isConfirmed { set; get; }

        [TempData]
        public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Not Found");

        public List<string> AllRoles { set; get; } = new List<string>();

        public async Task<IActionResult> OnPost()
        {


            var user = await _userManager.FindByIdAsync(Input.ID);
            if (user == null)
            {
                return NotFound("Cannot find user");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var allroles = await _roleManager.Roles.ToListAsync();

            allroles.ForEach((r) => {
                AllRoles.Add(r.Name);
            });

            if (!isConfirmed)
            {
                Input.RoleNames = roles.ToArray();
                isConfirmed = true;
                StatusMessage = "";
                ModelState.Clear();
            }
            else
            {
                StatusMessage = "Updated";
                if (Input.RoleNames == null) Input.RoleNames = new string[] { };
                foreach (var rolename in Input.RoleNames)
                {
                    if (roles.Contains(rolename)) continue;
                    await _userManager.AddToRoleAsync(user, rolename);
                }
                foreach (var rolename in roles)
                {
                    if (Input.RoleNames.Contains(rolename)) continue;
                    await _userManager.RemoveFromRoleAsync(user, rolename);
                }

            }

            Input.Name = user.UserName;
            return Page();
        }
    }
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EnterpriseWebApplication.Areas.Admin.Pages.Role
{
    public class IndexModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public IndexModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public List<IdentityRole> roles { set; get; }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGet()
        {
            roles = await _roleManager.Roles.ToListAsync();
            return Page();
        }
    }
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EnterpriseWebApplication.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EnterpriseWebApplication.Areas.Admin.Pages.Role
{
    public class UserModel : PageModel
    {
        const int USER_PER_PAGE = 10;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public UserModel(RoleManager<IdentityRole> roleManager,
                          UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public class UserInList : AppUser
        {
            public string listroles { set; get; }
        }

        public List<UserInList> users;
        public int totalPages { set; get; }

        [TempData] 
        public string StatusMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public int pageNumber { set; get; }

        public IActionResult OnPost() => NotFound("No posting");

        public async Task<IActionResult> OnGet()
        {

            var cuser = await _userManager.GetUserAsync(User);
            await _userManager.AddToRolesAsync(cuser, new string[] { "Admin" });

            if (pageNumber == 0)
                pageNumber = 1;

            var lusers = (from u in _userManager.Users
                          orderby u.UserName
                          select new UserInList()
                          {
                              Id = u.Id,
                              UserName = u.UserName,
                          });


            int totalUsers = await lusers.CountAsync();


            totalPages = (int)Math.Ceiling((double)totalUsers / USER_PER_PAGE);

            users = await lusers.Skip(USER_PER_PAGE * (pageNumber - 1)).Take(USER_PER_PAGE).ToListAsync();

            // users.ForEach(async (user) => {
            //     var roles = await _userManager.GetRolesAsync(user);
            //     user.listroles = string.Join(",", roles.ToList());
            // });

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.listroles = string.Join(",", roles.ToList());
            }

            return Page();
        }
    }
}

EnterpriseWebApplication/Controllers/User/UserIdeasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnterpriseWebApplication.Data;
using EnterpriseWebApplication.Models.Entities;

namespace EnterpriseWebApplication.Controllers.User
{
    public class UserIdeasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserIdeasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserIdeas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Ideas.Include(n => n.Category).Include(n => n.Submission);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: UserIdeas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nIdea = await _context.Ideas
                .Include(n => n.Category)
                .Include(n => n.Submission)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nIdea == null)
            {
                return NotFound();
            }

            return View(nIdea);
        }

        // GET: UserIdeas/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["SubmissionId"] = new SelectList(_context.Submissions, "Id", "Id");
            return View();
        }

        // POST: UserIdeas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Brief,Content,FilePath,View,SubmissionId,CategoryId,UserId,Id,CreatedDate,UpdatedDate")] NIdea nIdea)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nIdea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", nIdea.CategoryId);
            ViewData["SubmissionId"] = new SelectList(_context.Submissions, "Id", "Id", nIdea.SubmissionId);
            return View(nIdea);
        }

        // GET: UserIdeas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nIdea = await _context.Ideas.FindAsync(id);
            if (nIdea == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", nIdea.CategoryId);
            ViewData["SubmissionId"] = new SelectList(_context.Submissions, "Id", "Id", nIdea.SubmissionId);
            return View(nIdea);
        }

        // POST: UserIdeas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Brief,Content,FilePath,View,SubmissionId,CategoryId,UserId,Id,CreatedDate,UpdatedDate")] NIdea nIdea)
        {
            if (id != nIdea.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nIdea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NIdeaExists(nIdea.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", nIdea.CategoryId);
            ViewData["SubmissionId"] = new SelectList(_context.Submissions, "Id", "Id", nIdea.SubmissionId);
            return View(nIdea);
        }

        // GET: UserIdeas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nIdea = await _context.Ideas
                .Include(n => n.Category)
                .Include(n => n.Submission)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nIdea == null)
            {
                return NotFound();
            }

            return View(nIdea);
        }

        // POST: UserIdeas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nIdea = await _context.Ideas.FindAsync(id);
            _context.Ideas.Remove(nIdea);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NIdeaExists(int id)
        {
            return _context.Ideas.Any(e => e.Id == id);
        }
    }
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/Add.cshtml
@page "/admin/role/updaterole/{handler?}/"
@model EnterpriseWebApplication.Areas.Admin.Pages.Role.AddModel
@{
    var btnText = Model.IsUpdate ? "Update" : "Create   ";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="IsUpdate">
            <div class="form-group">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <button id="add-or-edit-role" type="submit"
                    asp-page-handler="AddOrUpdate" class="btn btn-primary">
                @btnText
                </button>

                <a class="btn btn-primary" asp-page="./Index">Return</a>
            </form>
        </div>
    </div>

    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }

EnterpriseWebApplication/Areas/Admin/Pages/Role/AddUserRole.cshtml
@page
@model EnterpriseWebApplication.Areas.Admin.Pages.Role.AddUserRoleModel
@{
    ViewData["Title"] = "Add Role To a User";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Choose a role for <strong>@Model.Input.Name</strong></p>
        <form method="post">
            <partial name="_StatusMessage" model="@Model.StatusMessage" />
            <div class="form-group">
                @Html.LabelFor(x => x.Input.RoleNames)
                @Html.ListBoxFor(x => x.Input.RoleNames,
                    new SelectList(Model.AllRoles),
                    new { @class = "w-100", id = "selectrole" })
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./User">List</a>
            <button type="submit" class="btn btn-danger">Update</button>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/lib/multiple-select/multiple-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multiple-select/multiple-select.min.css" />
    <script>
          $('#selectrole').multipleSelect({
                selectAll: false,
                keepOpen: false,
                isOpen: false
            });
    </script>


    <partial name="_ValidationScriptsPartial" />
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/Delete.cshtml
@page
@model EnterpriseWebApplication.Areas.Admin.Pages.Role.DeleteModel
@{
    ViewData["Title"] = "Delete role";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Are you sure you want to delete <strong>@Model.Input.Name</strong> </p>
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./Index">Return</a>
            <button type="submit" asp-page="./Delete" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

EnterpriseWebApplication/Areas/Admin/Pages/Role/Index.cshtml
@page "/admin/role/"
@model EnterpriseWebApplication.Areas.Admin.Pages.Role.IndexModel

<h3>ROLE LIST</h3>
    <partial name="_StatusMessage" model="@Model.StatusMessage" />

    <form method="POST" class="my-1 d-inline">
        <button class="btn btn-secondary" asp-page="./Add"
                asp-page-handler="StartNewRole">
            Add New Role
        </button>
    </form>
    <a class="btn btn-secondary" asp-page="./User">Add role to a user</a>

    <table class="table">
        <tr>
            <th>Name</th>
            <th>Task</th>
        </tr>
        @foreach (var role in @Model.roles)
        {
            <tr>
                <td>@role.Name</td>
                <td>
                    <form method="POST" class="d-inline">
                        <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                                asp-page="./Add" asp-page-handler="StartUpdate">
                            Update Role
                        </button>
                    </form>
                    <form method="POST" class="d-inline">
                        <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                                asp-page="./Delete">
                            Delete Role
                        </button>
                    </form>
                </td>
            </tr>
        }
    </table>

EnterpriseWebApplication/Areas/Admin/Pages/Role/User.cshtml
@page "/admin/role/users/"
@model EnterpriseWebApplication.Areas.Admin.Pages.Role.UserModel
@{
    ViewData["Title"] = "USER LIST";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<a class="btn btn-primary" asp-page="./Index">Return</a>

<table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>Roles</th>
        <th>Actions</th>
    </tr>
    @foreach (var user in @Model.users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.listroles</td>
            <td>
                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@user.Id" class="btn btn-primary btn-sm"
                            asp-page="./AddUserRole">
                        Update Role
                    </button>
                </form>
            </td>
        </tr>

    }
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
@{

    Func<int?, string> generateUrl = (int? _pagenumber) =>
    {
        return Url.Page("./User", new { pageNumber = _pagenumber });
    };

    var datapaging = new
    {
        currentPage = Model.pageNumber,
        countPages = Model.totalPages,
        generateUrl = generateUrl
    };

}
<partial name="_Paging" model="@datapaging" />

EnterpriseWebApplication/Areas/Admin/Pages/Role/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}